### ISSUE TITLE
Install asset in laravel 4.2

### ISSUE THREAD

**Issue by jacksontong** [teepluss/laravel4-asset#6]
How can I install asset in laravel 4.2, I got this problem when run composer update: 
teepluss/asset dev-master requires illuminate/support 4.0.x -> satisfiable by illuminate/support[v4.0.0, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9]

But I'm using laravel 4.2 and my illuminate/support depen on my laravel version is 4.2, please fix it.

**Comment by dennisenderink** [comment]
As this repository hasn't been updated in a year I've forked and updated it so that it works with Illuminate\Support 4.x, I also added it to Packagist: https://packagist.org/packages/dennisenderink/asset.

**Comment by jacksontong** [comment]
thank you!

**Comment by MECU** [comment]
There already was another fork: https://github.com/dragonfire1119/laravel-4-asset
